name: dxf
description: DXF package for Dart developers to create, read, update and delete the data in AutoCAD DXF file - a CAD data file format developed by Autodesk.
version: 3.1.1
homepage: https://github.com/chuyentt/dxf

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  test: ^1.20.2
